"""glinet4 - A Python library for GL.iNet routers"""

from ._types import (
    AdguardConfig,
    Client,
    ClientsStatus,
    DiskInfo,
    DiskUsage,
    DmzConfig,
    EthernetPortStatus,
    FirmwareCheck,
    FlowStatsApp,
    FlowStatsRule,
    LedConfig,
    MloConfig,
    NetworkAcceleration,
    NetworkInterfaceStatus,
    PortForwardRule,
    RouterInfo,
    RouterStatus,
    TailscaleConfig,
    TailscaleExitNode,
    TailscaleStatus,
    TimezoneConfig,
    TorConfig,
    TrafficSpeed,
    UpgradeConfig,
    UsbInfoEntry,
    WanAccessConfig,
    WanCableState,
    WanInterfaceAddress,
    WanInterfaceInfo,
    WanIPv4Status,
    WanStatus,
    WifiIface,
    WifiNetwork,
    WifiRadioStatus,
    WireguardClientConfig,
    WireguardClientStatus,
    ZerotierConfig,
)
from .enums import TailscaleConnection
from .error_handling import FeatureConflictError
from .glinet import GLinet

__all__ = [
    "GLinet",
    "TailscaleConnection",
    "FeatureConflictError",
    "AdguardConfig",
    "Client",
    "ClientsStatus",
    "DiskInfo",
    "DiskUsage",
    "DmzConfig",
    "EthernetPortStatus",
    "FirmwareCheck",
    "FlowStatsApp",
    "FlowStatsRule",
    "LedConfig",
    "MloConfig",
    "NetworkAcceleration",
    "NetworkInterfaceStatus",
    "PortForwardRule",
    "RouterInfo",
    "RouterStatus",
    "TailscaleConfig",
    "TailscaleExitNode",
    "TailscaleStatus",
    "TimezoneConfig",
    "TorConfig",
    "TrafficSpeed",
    "UpgradeConfig",
    "UsbInfoEntry",
    "WanAccessConfig",
    "WanCableState",
    "WanInterfaceAddress",
    "WanInterfaceInfo",
    "WanIPv4Status",
    "WanStatus",
    "WifiIface",
    "WifiNetwork",
    "WifiRadioStatus",
    "WireguardClientConfig",
    "WireguardClientStatus",
    "ZerotierConfig",
]
