"""gli4py - A Python library for GL.iNet routers"""

from ._types import (
    Client,
    ClientsStatus,
    DiskInfo,
    DiskUsage,
    EthernetPortStatus,
    FirmwareCheck,
    MloConfig,
    NetworkInterfaceStatus,
    RouterInfo,
    RouterStatus,
    TailscaleConfig,
    TailscaleStatus,
    TimezoneConfig,
    TrafficSpeed,
    UpgradeConfig,
    UsbInfoEntry,
    WanCableState,
    WanInterfaceAddress,
    WanInterfaceInfo,
    WanIPv4Status,
    WanStatus,
    WifiIface,
    WifiRadioStatus,
    WireguardClientConfig,
    WireguardClientStatus,
)
from .enums import TailscaleConnection
from .glinet import GLinet

__all__ = [
    "GLinet",
    "TailscaleConnection",
    "Client",
    "ClientsStatus",
    "DiskInfo",
    "DiskUsage",
    "EthernetPortStatus",
    "FirmwareCheck",
    "MloConfig",
    "NetworkInterfaceStatus",
    "RouterInfo",
    "RouterStatus",
    "TailscaleConfig",
    "TailscaleStatus",
    "TimezoneConfig",
    "TrafficSpeed",
    "UpgradeConfig",
    "UsbInfoEntry",
    "WanCableState",
    "WanInterfaceAddress",
    "WanInterfaceInfo",
    "WanIPv4Status",
    "WanStatus",
    "WifiIface",
    "WifiRadioStatus",
    "WireguardClientConfig",
    "WireguardClientStatus",
]
